//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Charity_Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Footer
    {
        public int FooterId { get; set; }
        public string Address_Eng { get; set; }
        public string Address_Tr { get; set; }
        public string Address_Ar { get; set; }
        public string Contact1 { get; set; }
        public string Contact2 { get; set; }
        public string Email { get; set; }
        public string CopyWrite_Eng { get; set; }
        public string CopyWrite_Tr { get; set; }
        public string CopyWrite_Ar { get; set; }
    }
}
