//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Charity_Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gallary
    {
        public int Id { get; set; }
        public string ImagePath { get; set; }
        public string TitleAr { get; set; }
        public string TitleEn { get; set; }
        public string TitleTu { get; set; }
        public string IsDeleted { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    }
}
