//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Charity_Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member
    {
        public int MemeberId { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string Country { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string SurName { get; set; }
        public string Province { get; set; }
        public string District { get; set; }
        public string Gender { get; set; }
    }
}
